### ISSUE TITLE
Update PageImporter to use MediaWiki\Storage\PageUpdater saveRevision

### ISSUE THREAD

**Issue by djflux** [djflux/PageImporter#1]
The current PageImporter.class.php uses WikiPage::doEditContent when importing a page. That method was deprecated in Mediwiki 1.32 and removed in MediaWiki 1.36.

The current recommended method is to use PageUpdater:saveRevision as per 

https://doc.wikimedia.org/mediawiki-core/REL1_39/php/classWikiPage.html#a9aeff9c38d314ecb631af379213094dc

Update PageImporter to use PageUpdater:saveRevision.

This issue is related to djflux/meza/issues/31

**Comment by djflux** [comment]
Using this code as an example for `saveRevision`

https://github.com/wikimedia/mediawiki-extensions-CreateRedirect/blob/master/SpecialCreateRedirect.php

**Comment by djflux** [comment]
Getting this error when running `meza deploy monolith` with current 0.1.0-mw-1.39 branch. Working on fix.

```
58215cb3b1f837dbc22c22c0] [no req]   TypeError: MediaWiki\Page\WikiPageFactory::newFromTitle(): Argument #1 ($pageIdentity) must be of type MediaWiki\Page\PageIdentity, string given, called in /opt/htdocs/mediawiki/extensions/PageImporter/PageImporter.class.php on line 109
Backtrace:
from /opt/htdocs/mediawiki/includes/page/WikiPageFactory.php(50)
#0 /opt/htdocs/mediawiki/extensions/PageImporter/PageImporter.class.php(109): MediaWiki\Page\WikiPageFactory->newFromTitle(string)
#1 /opt/htdocs/mediawiki/extensions/PageImporter/importPages.php(71): PageImporter->import(PageImporterImportPages, boolean)
#2 /opt/htdocs/mediawiki/maintenance/includes/MaintenanceRunner.php(309): PageImporterImportPages->execute()
#3 /opt/htdocs/mediawiki/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#4 /opt/htdocs/mediawiki/extensions/PageImporter/importPages.php(86): require_once(string)
#5 {main}


MSG:

non-zero return code

```
